language: node_js

node_js:
  - "0.10"

services:
  - cassandra

before_install:
  - echo "127.0.0.1 " `hostname` | sudo tee /etc/hosts
  - sudo sh -c "echo 'JVM_OPTS=\"\${JVM_OPTS} -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra stop
  - sudo service cassandra start
  - sudo service cassandra status

script:
  - npm test

notifications:
    hipchat:
        secure: "fPlQmSh5x85hFv8tjG/0LcQayHFjll1R5svC2nEZ6Jp51Ymdw9l6tVZ+X3Mq1WrqB40hehlHw2W7QM9hhK/2iFDvR/SQKYHodmVCuKFioYpgLsCRHsu3mEjiGmd/3whIA8v6tDa5AAfpic3HFVXPzs0IV/cbe2y3TUddmVDqFGk="
    webhooks:
        secure: "kRhZpReiZD1m6qtxZ8RFq1VXH0TZH66i20rDxoMQnoPxn1RDB+VxtcC4MG/lSlLQpk+brehjioRNOVLm8idwqJoCu3VhWqZ70TdgkCNws9rFiXgjy6DYfg56/wwsjXNZYAiW2ymdHa5HpEYHsD2x69En6AvwuLfltxKg0+yL+iM="
